name: CI

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "cli/**"
      - "functions/**"
      - "shared/**"
      - "Cargo*"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/ci.yml"
      - "cli/**"
      - "functions/**"
      - "shared/**"
      - "Cargo*"

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  RUSTFLAGS: "-C debuginfo=0 -C link-arg=-fuse-ld=bfd -C strip=symbols"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: mozilla-actions/sccache-action@v0.0.11
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache cargo registry
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Expand swap
        run: |
          sudo fallocate -l 4G /swapfile2
          sudo chmod 600 /swapfile2
          sudo mkswap /swapfile2
          sudo swapon /swapfile2
      - uses: actions/checkout@v7
      - uses: mozilla-actions/sccache-action@v0.0.11
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo registry
        uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - run: cargo test --workspace
      - run: cargo test --workspace --all-features --no-run
